#!/usr/bin/env python3
from datetime import date
import socket
import json

print("Cache-Control:no-cache")
print("Content-Type:text/html\r\n\r\n")

print("<html>")
print("<head><title>Hello CGI World</title></head>")
print("<body>")

today = date.today()
hostname = socket.gethostname()
ip = socket.gethostbyname(hostname)
message = {
    "title": "Hello, Python", 
    "heading": "Hello, Python",
    "message": "This page was generated by the Python programming language",
    "time": today.strftime("%B %d, %Y"),
    "ip": ip,
}
print("<p>", json.dumps(message), "</p>")


print("</body></html>")